name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: pdcmoreira/release-drafter@manually-set-tag
        with:
          tag: 'v2.1.1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
